services:
  flyer-server:
    image: ym-flyer-server:latest
    container_name: ym-flyer-server
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - local-config.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/health/" ]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    container_name: pg-store
    image: postgres
    hostname: pg-store
    ports:
      - "5432:5432"
    env_file:
      - local-config.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data: