services:
  ym-flyer-gen-server:
    image: ym-flyer-gen-server:latest
    container_name: ym-flyer-gen-server
    build: .
    ports:
      - "8080:8080"
    # depends_on:
    env_file:
      - local-config.env
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/api/v1/health/" ]
      interval: 30s
      timeout: 10s
      retries: 3