name: build

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch: {}
concurrency:
  group: 'shoaib-pipe-store-inventory-${{ github.ref }}'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.4'

      - name: Lint
        run: |
          unformatted=$(gofmt -l .)
          if [ -n "$unformatted" ]; then
            echo "The following files need formatting:"
            echo "$unformatted"
            echo "Diff of formatting changes needed:"
            gofmt -d $unformatted
            exit 1
          fi

      - name: Build
        run: go build -v -race ./...

      # Enable once tests are written
      # - name: Test
      #   run: go test -v